"""
    LanXin+ OpenAPI

    LanXin+ OpenAPI Platform  # noqa: E501

    Generated by: https://openapi.lanxin.cn
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "lanxinplus-openapi"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

with open('README.rst', 'rb') as f:
    long_description = f.read().decode('utf-8')

setup(
    name=NAME,
    version=VERSION,
    description="LanXin+ OpenAPI",
    author="API Support",
    author_email="open@comisys.net",
    url="",
    keywords=["LanXin+ OpenAPI"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description=long_description
)
